# Generated by Django 6.0.6 on 2026-06-10 19:56

import fhir_mapping_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FhirSyncLog',
            fields=[
                ('id', models.UUIDField(default=fhir_mapping_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=100)),
                ('internal_id', models.UUIDField()),
                ('sync_status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fhir_sync_logs',
            },
        ),
        migrations.CreateModel(
            name='FhirResourceMapping',
            fields=[
                ('id', models.UUIDField(default=fhir_mapping_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('fhir_resource_type', models.CharField(max_length=100)),
                ('internal_model', models.CharField(max_length=100)),
                ('mapping_schema', models.JSONField(help_text='JSON mapping rules from internal to FHIR standard')),
                ('version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fhir_resource_mappings',
                'unique_together': {('fhir_resource_type', 'version')},
            },
        ),
    ]
