# Generated by Django 6.0.6 on 2026-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysissession',
            name='access_type',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='blood_flow_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='dialysate_flow_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='machine_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='post_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='pre_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='ultrafiltration_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialysissession',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=50),
        ),
    ]
