# Generated by Django 6.0.6 on 2026-06-15 12:23

import django.db.models.deletion
import finance_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('manager_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fin_cost_centers',
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_accounting_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('is_header', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_posting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.costcenter')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance_app.glaccount')),
            ],
            options={
                'db_table': 'fin_gl_accounts',
                'ordering': ['code'],
                'unique_together': {('facility_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_app.glaccount')),
            ],
            options={
                'db_table': 'fin_bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('entry_number', models.CharField(max_length=30, unique=True)),
                ('entry_date', models.DateField()),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, help_text='billing|payroll|inventory|manual', max_length=50)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journals', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='finance_app.accountingperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fin_journal_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('insurer_id', models.UUIDField(blank=True, null=True)),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('paid', 'Paid'), ('bad_debt', 'Bad Debt'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('zatca_status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.journalentry')),
            ],
            options={
                'db_table': 'fin_ar_invoices',
            },
        ),
        migrations.CreateModel(
            name='APInvoice',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('vendor_id', models.UUIDField(help_text='procurement_app.Vendor')),
                ('po_id', models.UUIDField(blank=True, help_text='procurement_app.PurchaseOrder', null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('voided', 'Voided')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.journalentry')),
            ],
            options={
                'db_table': 'fin_ap_invoices',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance_app.glaccount')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.costcenter')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance_app.journalentry')),
            ],
            options={
                'db_table': 'fin_journal_lines',
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('txn_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reconciled', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='finance_app.bankaccount')),
                ('journal_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance_app.journalline')),
            ],
            options={
                'db_table': 'fin_bank_statements',
            },
        ),
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.UUIDField(default=finance_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance_app.costcenter')),
            ],
            options={
                'db_table': 'fin_annual_budgets',
                'unique_together': {('cost_center', 'fiscal_year')},
            },
        ),
    ]
