# Generated by Django 6.0.6 on 2026-06-10 19:56

import data_platform_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGovernanceRule',
            fields=[
                ('id', models.UUIDField(default=data_platform_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('target_table', models.CharField(max_length=100)),
                ('target_column', models.CharField(max_length=100)),
                ('masking_rule', models.CharField(max_length=100)),
                ('applicable_roles', models.JSONField(help_text='Roles that this masking applies to')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'data_governance_rules',
            },
        ),
        migrations.CreateModel(
            name='DataWarehouseStream',
            fields=[
                ('id', models.UUIDField(default=data_platform_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('source_table', models.CharField(max_length=100)),
                ('target_warehouse', models.CharField(max_length=100)),
                ('sync_frequency', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dw_streams',
            },
        ),
    ]
