# Generated by Django 6.0.6 on 2026-06-15 12:23

import django.db.models.deletion
import procurement_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'procurement_po_lines',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'procurement_suppliers',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('cr_number', models.CharField(blank=True, help_text='Commercial Registration', max_length=50)),
                ('zatca_tin', models.CharField(blank=True, help_text='VAT Registration Number', max_length=15)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.IntegerField(default=30, help_text='Net days')),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'procurement_vendors',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(max_length=30, unique=True)),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_grns',
            },
        ),
        migrations.CreateModel(
            name='GRNLine',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('received_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepted_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement_app.goodsreceiptnote')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement_app.poline')),
            ],
            options={
                'db_table': 'procurement_grn_lines',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('po_number', models.CharField(max_length=30, unique=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent to Vendor'), ('partial', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_purchase_orders',
            },
        ),
        migrations.AddField(
            model_name='poline',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement_app.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='procurement_app.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement_app.purchaseorder')),
            ],
            options={
                'db_table': 'procurement_purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('pr_number', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('required_by', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='draft', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_check_passed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_requisitions',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement_app.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='PRLine',
            fields=[
                ('id', models.UUIDField(default=procurement_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(blank=True, help_text='inventory_app.MedicalItem', null=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement_app.purchaserequisition')),
            ],
            options={
                'db_table': 'procurement_pr_lines',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement_app.vendor'),
        ),
    ]
