# Generated by Django 6.0.6 on 2026-06-10 19:56

import billing_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=billing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('encounter_id', models.UUIDField()),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'billing_invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=billing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing_app.invoice')),
            ],
            options={
                'db_table': 'billing_payments',
            },
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.UUIDField(default=billing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('encounter_id', models.UUIDField()),
                ('clinical_event_id', models.UUIDField(help_text='Reference to LabResult, MedicationAdministration, etc.')),
                ('service_code', models.CharField(help_text='Billing Code (e.g. CPT)', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicecharge_set', to='billing_app.invoice')),
            ],
            options={
                'db_table': 'billing_charges',
            },
        ),
    ]
