# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import pharmacy_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.UUIDField(default=pharmacy_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('prescribing_physician_id', models.UUIDField()),
                ('terminology_concept_id', models.UUIDField(help_text='RxNorm code for medication')),
                ('medication_name', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('prn_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pharmacy_orders',
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=pharmacy_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('administered_by', models.UUIDField(help_text='Nurse ID')),
                ('administered_at', models.DateTimeField(auto_now_add=True)),
                ('dose_given', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='pharmacy_app.medicationorder')),
            ],
            options={
                'db_table': 'pharmacy_administrations',
            },
        ),
        migrations.CreateModel(
            name='ControlledDrugRegister',
            fields=[
                ('id', models.UUIDField(default=pharmacy_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('dispensed_qty', models.FloatField()),
                ('dispensed_by', models.UUIDField(help_text='Primary Pharmacist')),
                ('verified_by', models.UUIDField(help_text='Second Pharmacist/Manager for 2-step verification')),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.medicationorder')),
            ],
            options={
                'db_table': 'pharmacy_controlled_drug_register',
            },
        ),
        migrations.CreateModel(
            name='ClinicalVerificationLog',
            fields=[
                ('id', models.UUIDField(default=pharmacy_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('pharmacist_id', models.UUIDField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='pharmacy_app.medicationorder')),
            ],
            options={
                'db_table': 'pharmacy_clinical_verifications',
            },
        ),
        migrations.CreateModel(
            name='PharmacyIntervention',
            fields=[
                ('id', models.UUIDField(default=pharmacy_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('pharmacist_id', models.UUIDField()),
                ('intervention_type', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='pharmacy_app.medicationorder')),
            ],
            options={
                'db_table': 'pharmacy_interventions',
            },
        ),
        migrations.CreateModel(
            name='RefillRequest',
            fields=[
                ('id', models.UUIDField(default=pharmacy_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('medication_name', models.CharField(max_length=255)),
                ('requested_by', models.UUIDField(help_text='User ID of requestor')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.medicationorder')),
            ],
            options={
                'db_table': 'pharmacy_refill_requests',
            },
        ),
        migrations.CreateModel(
            name='SmartDispenseLog',
            fields=[
                ('id', models.UUIDField(default=pharmacy_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('cabinet_id', models.CharField(max_length=100)),
                ('nurse_id', models.UUIDField()),
                ('dispensed_qty', models.FloatField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('medication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.medicationorder')),
            ],
            options={
                'db_table': 'pharmacy_dispense_logs',
            },
        ),
    ]
