# Generated by Django 6.0.6 on 2026-06-10 19:56

import experience_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientComplaint',
            fields=[
                ('id', models.UUIDField(default=experience_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('department', models.CharField(max_length=100)),
                ('complaint_text', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exp_complaints',
            },
        ),
        migrations.CreateModel(
            name='PatientSurvey',
            fields=[
                ('id', models.UUIDField(default=experience_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('survey_type', models.CharField(max_length=100)),
                ('nps_score', models.IntegerField(blank=True, null=True)),
                ('responses', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exp_surveys',
            },
        ),
    ]
