# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import rad_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.UUIDField(default=rad_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('ordering_physician_id', models.UUIDField()),
                ('modality', models.CharField(max_length=50)),
                ('body_part', models.CharField(max_length=100)),
                ('reason_for_exam', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rad_orders',
            },
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.UUIDField(default=rad_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('dicom_study_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('performed_by', models.UUIDField(help_text='Technician ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('pacs_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='rad_app.imagingorder')),
            ],
            options={
                'db_table': 'rad_studies',
            },
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.UUIDField(default=rad_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('radiologist_id', models.UUIDField()),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('ai_pre_read', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='rad_app.imagingstudy')),
            ],
            options={
                'db_table': 'rad_reports',
            },
        ),
    ]
