# Generated by Django 6.0.6 on 2026-06-15 12:23

import django.db.models.deletion
import inventory_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('id', models.UUIDField(default=inventory_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('medication', 'Medication'), ('consumable', 'Consumable'), ('equipment', 'Equipment'), ('reagent', 'Reagent'), ('vaccine', 'Vaccine'), ('linen', 'Linen')], max_length=20)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('sfda_code', models.CharField(blank=True, max_length=100)),
                ('requires_cold_chain', models.BooleanField(default=False)),
                ('is_controlled_drug', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_medical_items',
            },
        ),
        migrations.CreateModel(
            name='StorageFacility',
            fields=[
                ('id', models.UUIDField(default=inventory_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('store_type', models.CharField(default='general', help_text='general|pharmacy|theatre|lab|central', max_length=50)),
                ('is_cold_chain', models.BooleanField(default=False)),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_storage_facilities',
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=inventory_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory_app.medicalitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory_app.storagefacility')),
            ],
            options={
                'db_table': 'inventory_batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=inventory_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('receive', 'Receive (GRN)'), ('issue', 'Issue to Ward/Patient'), ('transfer', 'Inter-Store Transfer'), ('return', 'Return to Store'), ('writeoff', 'Write-Off'), ('disposal', 'Expiry Disposal'), ('adjust', 'Stock Adjustment')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='PO/Encounter/Transfer ref', max_length=100)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory_app.inventorybatch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_movements', to='inventory_app.storagefacility')),
                ('to_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_movements', to='inventory_app.storagefacility')),
            ],
            options={
                'db_table': 'inventory_stock_movements',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=inventory_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('near_expiry', 'Near Expiry (30 days)'), ('expired', 'Expired'), ('cold_breach', 'Cold Chain Breach')], max_length=20)),
                ('current_qty', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_app.inventorybatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.medicalitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.storagefacility')),
            ],
            options={
                'db_table': 'inventory_stock_alerts',
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.UUIDField(default=inventory_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('min_qty', models.IntegerField()),
                ('max_qty', models.IntegerField()),
                ('reorder_qty', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory_app.medicalitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.storagefacility')),
            ],
            options={
                'db_table': 'inventory_reorder_rules',
                'unique_together': {('item', 'store')},
            },
        ),
    ]
