# Generated by Django 6.0.6 on 2026-06-10 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hl7MessageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('message_type', models.CharField(max_length=50)),
                ('trigger_event', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(max_length=50)),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_system', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_message', models.TextField()),
                ('processing_status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('message_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hl7_messages',
            },
        ),
    ]
