# Generated by Django 6.0.6 on 2026-06-15 12:23

import crm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOutreach',
            fields=[
                ('id', models.UUIDField(default=crm_app.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('outreach_type', models.CharField(choices=[('followup_call', 'Follow-up Call'), ('appointment_reminder', 'Appointment Reminder'), ('preventive_care', 'Preventive Care Alert'), ('chronic_mgmt', 'Chronic Disease Management'), ('vaccination', 'Vaccination Reminder')], max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('call', 'Phone'), ('portal', 'Portal')], max_length=20)),
                ('message', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('responded', 'Responded')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'crm_outreach',
            },
        ),
        migrations.CreateModel(
            name='PatientSatisfactionSurvey',
            fields=[
                ('id', models.UUIDField(default=crm_app.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('survey_type', models.CharField(choices=[('hcahps', 'HCAHPS'), ('outpatient', 'Outpatient'), ('ed', 'Emergency'), ('discharge', 'Discharge')], max_length=30)),
                ('overall_score', models.IntegerField(blank=True, help_text='0-10', null=True)),
                ('responses', models.JSONField(default=dict)),
                ('nps_score', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crm_satisfaction_surveys',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=crm_app.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('referring_provider', models.UUIDField()),
                ('receiving_provider', models.UUIDField(blank=True, null=True)),
                ('receiving_facility', models.UUIDField(blank=True, null=True)),
                ('specialty', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crm_referrals',
            },
        ),
    ]
