version: '3.8'

services:
  backend:
    build: 
      context: ./cymed_python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] *

  frontend:
    build:
      context: ./cymed_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://52.28.86.77:8000
    depends_on:
      - backend
