# Generated by Django 6.0.6 on 2026-06-10 19:56

import onboarding_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.UUIDField(default=onboarding_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('error_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'onboarding_tasks',
            },
        ),
    ]
