# Generated by Django 6.0.6 on 2026-06-10 19:56

import ai_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGatewayLog',
            fields=[
                ('id', models.UUIDField(default=ai_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('intent', models.CharField(max_length=50)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_gateway_logs',
            },
        ),
        migrations.CreateModel(
            name='AITemplate',
            fields=[
                ('id', models.UUIDField(default=ai_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('intent', models.CharField(max_length=50)),
                ('system_prompt', models.TextField()),
                ('user_prompt_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ai_app_templates',
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=ai_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('was_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_app.aigatewaylog')),
            ],
            options={
                'db_table': 'ai_feedback',
            },
        ),
        migrations.CreateModel(
            name='AITokenUsage',
            fields=[
                ('id', models.UUIDField(default=ai_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='ai_app.aigatewaylog')),
            ],
            options={
                'db_table': 'ai_app_token_usage',
            },
        ),
    ]
