# Generated by Django 6.0.6 on 2026-06-10 19:56

import or_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthesiaLogs',
            fields=[
                ('id', models.UUIDField(default=or_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(help_text='Reference to OtCase')),
                ('recorded_by', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('anesthesia_type', models.CharField(max_length=100)),
                ('medications_given', models.JSONField(default=list)),
                ('vitals_snapshot', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'or_anesthesia_logs',
            },
        ),
        migrations.CreateModel(
            name='OtCase',
            fields=[
                ('id', models.UUIDField(default=or_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('surgeon_id', models.UUIDField()),
                ('anesthesiologist_id', models.UUIDField(blank=True, null=True)),
                ('procedure_code', models.UUIDField(help_text='Reference to Terminology App Concept (ICD-11/CPT)')),
                ('planned_procedure_name', models.CharField(max_length=255)),
                ('ot_room_id', models.UUIDField(help_text='Reference to SchedulableResource')),
                ('status', models.CharField(max_length=50)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('pre_op_diagnosis', models.TextField(blank=True, null=True)),
                ('post_op_diagnosis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'or_cases',
            },
        ),
        migrations.CreateModel(
            name='ProcedureLogs',
            fields=[
                ('id', models.UUIDField(default=or_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(help_text='Reference to OtCase')),
                ('recorded_by', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'or_procedure_logs',
            },
        ),
        migrations.CreateModel(
            name='SurgicalSafetyChecklist',
            fields=[
                ('id', models.UUIDField(default=or_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.UUIDField(help_text='Reference to OtCase')),
                ('phase', models.CharField(max_length=50)),
                ('completed_by', models.UUIDField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_data', models.JSONField(help_text='Checklist items and their status')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'or_surgical_safety_checklist',
            },
        ),
    ]
