# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import patient_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField()),
                ('encounter_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('attending_physician_id', models.UUIDField(blank=True, null=True)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_encounters',
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('note_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patient_app.encounter')),
            ],
            options={
                'db_table': 'clinical_notes',
            },
        ),
        migrations.CreateModel(
            name='GlobalPatient',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('global_patient_id', models.CharField(help_text='Enterprise-wide unique patient identifier', max_length=255, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True)),
                ('master_demographics', models.JSONField(help_text='Core demographic data (Name, DOB, Gender, etc.)')),
                ('identity_confidence_score', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('merge_status', models.CharField(default='UNMERGED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('surviving_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_records', to='patient_app.globalpatient')),
            ],
            options={
                'db_table': 'global_patients',
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('assigning_authority', models.CharField(max_length=255)),
                ('identifier_value', models.CharField(max_length=255)),
                ('identifier_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='patient_app.globalpatient')),
            ],
            options={
                'db_table': 'external_identifiers',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('primary_care_physician_id', models.UUIDField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('organ_donor_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('global_patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='patient_app.globalpatient')),
            ],
            options={
                'db_table': 'clinical_patients',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patient_app.patient'),
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('terminology_concept_id', models.UUIDField(blank=True, help_text='Reference to Terminology App Concept (ICD-11)', null=True)),
                ('condition_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('diagnosed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_app.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='patient_app.patient')),
            ],
            options={
                'db_table': 'clinical_conditions',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('terminology_concept_id', models.UUIDField(help_text='Reference to Terminology App Concept (RxNorm/SNOMED)')),
                ('allergy_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('reaction_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('recorded_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patient_app.patient')),
            ],
            options={
                'db_table': 'clinical_allergies',
            },
        ),
        migrations.CreateModel(
            name='PatientMergeLog',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('merged_by', models.UUIDField()),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('unmerged', models.BooleanField(default=False)),
                ('non_surviving_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_victim_logs', to='patient_app.globalpatient')),
                ('surviving_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_survivor_logs', to='patient_app.globalpatient')),
            ],
            options={
                'db_table': 'patient_merge_logs',
            },
        ),
        migrations.CreateModel(
            name='FacilityMRN',
            fields=[
                ('id', models.UUIDField(default=patient_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField()),
                ('local_mrn', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_mrns', to='patient_app.globalpatient')),
            ],
            options={
                'db_table': 'facility_mrns',
                'unique_together': {('facility_id', 'local_mrn')},
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'status'], name='clinical_en_patient_b821ca_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['facility_id', 'status'], name='clinical_en_facilit_b389cc_idx'),
        ),
    ]
