# Generated by Django 6.0.6 on 2026-06-10 19:56

import bed_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.UUIDField(default=bed_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('equipment_level', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=bed_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('ward_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bed_wards',
            },
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.UUIDField(default=bed_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.UUIDField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bed_app.bed')),
            ],
            options={
                'db_table': 'bed_assignments',
            },
        ),
        migrations.CreateModel(
            name='SurgeCapacityPlan',
            fields=[
                ('id', models.UUIDField(default=bed_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('trigger_threshold_percent', models.IntegerField()),
                ('additional_beds_possible', models.IntegerField()),
                ('action_plan', models.TextField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_app.ward')),
            ],
            options={
                'db_table': 'bed_surge_plans',
            },
        ),
        migrations.CreateModel(
            name='DailyCapacitySnapshot',
            fields=[
                ('id', models.UUIDField(default=bed_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('total_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bed_app.ward')),
            ],
            options={
                'db_table': 'bed_capacity_snapshots',
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='bed_app.ward'),
        ),
    ]
