# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import rpm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDevice',
            fields=[
                ('id', models.UUIDField(default=rpm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('device_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rpm_devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.UUIDField(default=rpm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpm_app.connecteddevice')),
            ],
            options={
                'db_table': 'rpm_readings',
            },
        ),
        migrations.CreateModel(
            name='RPMAlert',
            fields=[
                ('id', models.UUIDField(default=rpm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('alert_level', models.CharField(max_length=50)),
                ('status', models.CharField(default='NEW', max_length=50)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpm_app.devicereading')),
            ],
            options={
                'db_table': 'rpm_alerts',
            },
        ),
    ]
