# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import licensing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEdition',
            fields=[
                ('id', models.UUIDField(default=licensing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('included_modules', models.JSONField(default=list)),
                ('optional_modules', models.JSONField(default=list)),
                ('ai_features_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'licensing_product_editions',
            },
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.UUIDField(default=licensing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('feature_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'licensing_feature_toggles',
                'unique_together': {('tenant_id', 'feature_name')},
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.UUIDField(default=licensing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('key_string', models.CharField(max_length=255, unique=True)),
                ('tenant_id', models.UUIDField()),
                ('license_type', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing_app.productedition')),
            ],
            options={
                'db_table': 'licensing_keys',
            },
        ),
    ]
