# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import terminology_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologySystem',
            fields=[
                ('id', models.UUIDField(default=terminology_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'terminology_systems',
            },
        ),
        migrations.CreateModel(
            name='ClinicalConcept',
            fields=[
                ('id', models.UUIDField(default=terminology_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=500)),
                ('definition', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='terminology_app.terminologysystem')),
            ],
            options={
                'db_table': 'clinical_concepts',
            },
        ),
        migrations.CreateModel(
            name='ConceptMapping',
            fields=[
                ('id', models.UUIDField(default=terminology_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('mapping_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_from', to='terminology_app.clinicalconcept')),
                ('target_concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_to', to='terminology_app.clinicalconcept')),
            ],
            options={
                'db_table': 'concept_mappings',
                'unique_together': {('source_concept', 'target_concept', 'mapping_type')},
            },
        ),
        migrations.AddIndex(
            model_name='clinicalconcept',
            index=models.Index(fields=['code'], name='clinical_co_code_e4a18f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalconcept',
            index=models.Index(fields=['display_name'], name='clinical_co_display_77eb97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicalconcept',
            unique_together={('system', 'code')},
        ),
    ]
