# Generated by Django 6.0.6 on 2026-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalconcept',
            name='parent_uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clinicalconcept',
            name='uri',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
