# Generated by Django 6.0.6 on 2026-06-10 19:56

import cds_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRule',
            fields=[
                ('id', models.UUIDField(default=cds_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('condition_expression', models.TextField()),
                ('action_type', models.CharField(max_length=50)),
                ('action_payload', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cds_rules',
            },
        ),
    ]
