# Generated by Django 6.0.6 on 2026-06-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrule',
            name='action_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='clinicalrule',
            name='alert_level',
            field=models.CharField(default='INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='clinicalrule',
            name='domain',
            field=models.CharField(default='GENERAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinicalrule',
            name='action_payload',
            field=models.JSONField(default=dict),
        ),
    ]
