# Generated by Django 6.0.6 on 2026-06-10 19:56

import interop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteropMessageLog',
            fields=[
                ('id', models.UUIDField(default=interop_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=20)),
                ('source_system', models.CharField(max_length=100)),
                ('target_system', models.CharField(max_length=100)),
                ('raw_payload', models.TextField()),
                ('parsed_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interop_message_logs',
            },
        ),
    ]
