# Generated by Django 6.0.6 on 2026-06-10 19:56

import pophealth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpidemiologyAlert',
            fields=[
                ('id', models.UUIDField(default=pophealth_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('incident_count', models.IntegerField(default=0)),
                ('alert_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pophealth_alerts',
            },
        ),
    ]
