# Generated by Django 6.0.6 on 2026-06-15 12:23

import django.db.models.deletion
import payroll_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EOSBRecord',
            fields=[
                ('id', models.UUIDField(default=payroll_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('professional_id', models.UUIDField(db_index=True)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('hire_date', models.DateField()),
                ('end_date', models.DateField()),
                ('years_service', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eosb_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(help_text='resignation|termination|retirement', max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payroll_eosb_records',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=payroll_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('professional_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('month_year', models.CharField(max_length=20)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payroll_records',
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=payroll_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('basic', 'Basic Salary'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('overtime', 'Overtime'), ('bonus', 'Bonus')], max_length=15)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_gosi', models.BooleanField(default=False, help_text='Included in GOSI base')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payroll_salary_components',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=payroll_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('professional_id', models.UUIDField(db_index=True, help_text='hr_app.HealthcareProfessional')),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('on_call_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payroll_salary_structures',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=payroll_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_runs',
                'unique_together': {('facility_id', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.UUIDField(default=payroll_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('professional_id', models.UUIDField(db_index=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gosi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gosi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('working_days', models.IntegerField(default=30)),
                ('days_absent', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll_app.payrollrun')),
            ],
            options={
                'db_table': 'payroll_entries',
            },
        ),
    ]
