# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import rcm_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimLineItem',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.UUIDField()),
                ('service_charge_id', models.UUIDField()),
                ('cpt_code', models.CharField(max_length=50)),
                ('modifiers', models.JSONField(default=list)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('denial_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rcm_claim_line_items',
            },
        ),
        migrations.CreateModel(
            name='CPTCode',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('rvu', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'rcm_cpt_codes',
            },
        ),
        migrations.CreateModel(
            name='DenialAppeal',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.UUIDField()),
                ('assigned_to', models.UUIDField()),
                ('reason_code', models.CharField(max_length=50)),
                ('appeal_notes', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rcm_denial_appeals',
            },
        ),
        migrations.CreateModel(
            name='DRG',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'rcm_drgs',
            },
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rcm_icd10_codes',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('payer_id', models.UUIDField(blank=True, null=True)),
                ('state', models.CharField(default='DRAFT', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rcm_insurance_claims',
            },
        ),
        migrations.CreateModel(
            name='MedicalCodingRecord',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField(unique=True)),
                ('coder_id', models.UUIDField()),
                ('drg_code', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_diagnosis_code', models.CharField(max_length=50)),
                ('secondary_diagnosis_codes', models.JSONField(default=list)),
                ('procedure_codes', models.JSONField(default=list)),
                ('status', models.CharField(max_length=50)),
                ('coded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rcm_coding_records',
            },
        ),
        migrations.CreateModel(
            name='EOB',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('patient_responsibility', models.DecimalField(decimal_places=2, max_digits=12)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eobs', to='rcm_app.insuranceclaim')),
            ],
            options={
                'db_table': 'rcm_eobs',
            },
        ),
        migrations.CreateModel(
            name='CDIQuery',
            fields=[
                ('id', models.UUIDField(default=rcm_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('physician_id', models.UUIDField()),
                ('coder_id', models.UUIDField()),
                ('query_text', models.TextField()),
                ('physician_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('coding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdi_queries', to='rcm_app.medicalcodingrecord')),
            ],
            options={
                'db_table': 'rcm_cdi_queries',
            },
        ),
    ]
