# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import scheduling_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulableResource',
            fields=[
                ('id', models.UUIDField(default=scheduling_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'schedulable_resources',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=scheduling_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('appointment_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='scheduling_app.schedulableresource')),
            ],
            options={
                'db_table': 'appointments',
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='appointment_start_t_d798d8_idx'), models.Index(fields=['patient_id'], name='appointment_patient_75a4eb_idx')],
            },
        ),
    ]
