# Generated by Django 6.0.6 on 2026-06-10 19:56

import integrity_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=integrity_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('claim_id', models.UUIDField()),
                ('provider_id', models.UUIDField()),
                ('alert_type', models.CharField(max_length=100)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='INVESTIGATING', max_length=50)),
            ],
            options={
                'db_table': 'integrity_fraud_alerts',
            },
        ),
    ]
