apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cymed-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/websocket-services: "cymed-api"
spec:
  ingressClassName: nginx
  rules:
  - host: cymed.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cymed-web
            port:
              number: 80
  - host: api.cymed.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cymed-api
            port:
              number: 80
