# Generated by Django 6.0.6 on 2026-06-10 19:56

import national_health_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalProviderRegistry',
            fields=[
                ('id', models.UUIDField(default=national_health_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('npi_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('is_active_license', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'national_provider_registry',
            },
        ),
    ]
