# Generated by Django 6.0.6 on 2026-06-10 19:56

import credentialing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.UUIDField(default=credentialing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField()),
                ('facility_id', models.UUIDField()),
                ('privilege_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('granted_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('approved_by', models.UUIDField()),
            ],
            options={
                'db_table': 'cred_privileges',
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.UUIDField(default=credentialing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.UUIDField(help_text='Reference to auth_app User/Employee')),
                ('credential_type', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('credential_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cred_provider_credentials',
            },
        ),
    ]
