"""
Django settings for cymed_core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY must be set via environment variable — no insecure fallback in production
_secret_key_default = 'django-insecure-dev-only-key-change-in-production' if os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't') else None
SECRET_KEY = os.environ.get('SECRET_KEY', _secret_key_default)
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable must be set in production")

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

# Explicit allowlist — never use ['*'] in production
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'auth_app',
    'patient_app',
    'ai_platform',
    'pharmacy_app',
    'lab_app',
    'rad_app',
    'bed_app',
    'nursing_app',
    'admission_app',
    'icu_app',
    'or_app',
    'finance_app',
    'billing_app',
    'insurance_app',
    'rcm_app',
    'hl7_engine',
    'zatca_compliance',
    'corsheaders',
    'cds_app',
    'predictive_app',
    'pophealth_app',
    'guardian',
    'audit_log_app',
    'credentialing_app',
    'scheduling_app',
    'infection_control_app',
    'stewardship_app',
    'home_health_app',
    'hospice_app',
    'rehab_app',
    'occ_health_app',
    'pathways_app',
    'knowledge_app',
    'experience_app',
    'equipment_app',
    'rtls_app',
    'terminology_app',
    'fhir_mapping_app',
    'event_catalog_app',
    'data_platform_app',
    'governance_app',
    'crm_app',
    'research_app',
    'analytics_app',
    'hr_app',
    'payroll_app',
    'procurement_app',
    'inventory_app',
    'asset_management_app',
    'national_health_app',
    'citizen_health_app',
    'blood_bank_app',
    'dialysis_app',
    'oncology_app',
    'cardiology_app',
    'pediatrics_app',
    'maternity_app',
    'dental_app',
    'education_app',
    'command_center_app',
    'ai_app',
    'interop_app',
    'reporting_app',
    'care_management_app',
    'rpm_app',
    'integrity_app',
    'um_app',
    'executive_app',
    'licensing_app',
    'saas_app',
    'onboarding_app',
    'support_app',
    'customer_success_app',
    'drf_spectacular',
    # New apps added in Phase 2-5
    'consent_app',
    'icd11_app',
    # Ported from CyMed-Antigravity (commercial-completeness pass)
    'calendar_app',
    'clinical_app',
    'coupons_app',
    'fleet_app',
    'helpdesk_app',
    'marketing_app',
    'messenger_app',
    'ops_app',
    'pos_app',
    'ninja',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'audit_log_app.middleware.AuditLogMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cymed_core.middleware.TenantScopeMiddleware',
]

ROOT_URLCONF = 'cymed_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'cymed_core.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR}/db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000').split(',')

AUTH_USER_MODEL = 'auth_app.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CyMed National Health Ecosystem API',
    'DESCRIPTION': 'Master API documentation for all 54 CyMed enterprise applications.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

# Celery Configuration Options
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Sentry is optional — only initialize if installed and DSN provided
_SENTRY_DSN = os.environ.get("SENTRY_DSN", "")
if _SENTRY_DSN:
    try:
        import sentry_sdk
        sentry_sdk.init(
            dsn=_SENTRY_DSN,
            traces_sample_rate=1.0,
            profiles_sample_rate=1.0,
        )
    except ImportError:
        pass
