# Generated by Django 6.0.6 on 2026-06-10 19:56

import zatca_compliance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZatcaInvoice',
            fields=[
                ('id', models.UUIDField(default=zatca_compliance.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.UUIDField(help_text='Reference to billing_app.Invoice')),
                ('zatca_uuid', models.UUIDField(unique=True)),
                ('invoice_hash', models.CharField(max_length=255)),
                ('xml_content', models.TextField()),
                ('qr_code_base64', models.TextField()),
                ('clearance_status', models.CharField(max_length=50)),
                ('clearance_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'zatca_invoices',
            },
        ),
    ]
