# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import predictive_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModelRegistry',
            fields=[
                ('id', models.UUIDField(default=predictive_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'predictive_models',
            },
        ),
        migrations.CreateModel(
            name='PatientRiskScore',
            fields=[
                ('id', models.UUIDField(default=predictive_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('score_value', models.FloatField()),
                ('risk_category', models.CharField(max_length=50)),
                ('factors', models.JSONField(help_text='Contributing factors to the score')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictive_app.predictivemodelregistry')),
            ],
            options={
                'db_table': 'predictive_patient_scores',
            },
        ),
    ]
