# Generated by Django 6.0.6 on 2026-06-10 23:39

import predictive_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictive_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=predictive_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('factors', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'predictive_risk_scores',
            },
        ),
    ]
