# Generated by Django 6.0.6 on 2026-06-10 19:56

import icu_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousVitals',
            fields=[
                ('id', models.UUIDField(default=icu_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('systolic_bp', models.FloatField(blank=True, null=True)),
                ('diastolic_bp', models.FloatField(blank=True, null=True)),
                ('map', models.FloatField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('respiratory_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'icu_continuous_vitals',
            },
        ),
        migrations.CreateModel(
            name='GCS',
            fields=[
                ('id', models.UUIDField(default=icu_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.UUIDField()),
                ('eye_opening', models.IntegerField()),
                ('verbal_response', models.IntegerField()),
                ('motor_response', models.IntegerField()),
                ('total_score', models.IntegerField()),
            ],
            options={
                'db_table': 'icu_gcs',
            },
        ),
        migrations.CreateModel(
            name='IcuFlowsheet',
            fields=[
                ('id', models.UUIDField(default=icu_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('recorded_by', models.UUIDField()),
                ('vent_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('fio2', models.FloatField(blank=True, null=True)),
                ('peep', models.FloatField(blank=True, null=True)),
                ('gcs_score', models.IntegerField(blank=True, null=True)),
                ('rass_score', models.IntegerField(blank=True, null=True)),
                ('pupil_response', models.CharField(blank=True, max_length=50, null=True)),
                ('drips', models.JSONField(help_text='Active vasopressors/sedation drips and rates')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'icu_flowsheets',
            },
        ),
        migrations.CreateModel(
            name='SOFAScore',
            fields=[
                ('id', models.UUIDField(default=icu_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('respiration_score', models.IntegerField(default=0)),
                ('coagulation_score', models.IntegerField(default=0)),
                ('liver_score', models.IntegerField(default=0)),
                ('cardiovascular_score', models.IntegerField(default=0)),
                ('cns_score', models.IntegerField(default=0)),
                ('renal_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField()),
            ],
            options={
                'db_table': 'icu_sofa_score',
            },
        ),
        migrations.CreateModel(
            name='VentilatorSettings',
            fields=[
                ('id', models.UUIDField(default=icu_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.UUIDField()),
                ('vent_mode', models.CharField(max_length=50)),
                ('fio2', models.FloatField()),
                ('peep', models.FloatField()),
                ('tidal_volume', models.FloatField(blank=True, null=True)),
                ('resp_rate', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'icu_ventilator_settings',
            },
        ),
    ]
