# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import equipment_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.UUIDField(default=equipment_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('equipment_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('facility_id', models.UUIDField()),
                ('current_location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('next_maintenance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equip_assets',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=equipment_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('performed_by', models.UUIDField()),
                ('maintenance_type', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='equipment_app.medicalequipment')),
            ],
            options={
                'db_table': 'equip_maintenance_logs',
            },
        ),
    ]
