# Generated by Django 6.0.6 on 2026-06-10 19:56

import citizen_health_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenAccount',
            fields=[
                ('id', models.UUIDField(default=citizen_health_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('linked_patient_ids', models.JSONField(default=list)),
                ('consent_for_research', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'citizen_accounts',
            },
        ),
    ]
