# Generated by Django 6.0.6 on 2026-06-10 19:56

import um_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorAuthorization',
            fields=[
                ('id', models.UUIDField(default=um_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('procedure_code', models.CharField(max_length=50)),
                ('payer_id', models.UUIDField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'um_prior_auths',
            },
        ),
        migrations.CreateModel(
            name='UtilizationReview',
            fields=[
                ('id', models.UUIDField(default=um_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('review_type', models.CharField(max_length=50)),
                ('findings', models.TextField()),
                ('is_medically_necessary', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'um_reviews',
            },
        ),
    ]
