# Generated by Django 6.0.6 on 2026-06-10 19:56

import analytics_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveDashboardConfig',
            fields=[
                ('id', models.UUIDField(default=analytics_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('layout_json', models.JSONField(help_text="User's customized dashboard layout")),
                ('default_facility_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_dashboard_configs',
            },
        ),
        migrations.CreateModel(
            name='KpiSnapshot',
            fields=[
                ('id', models.UUIDField(default=analytics_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('kpi_name', models.CharField(max_length=100)),
                ('facility_id', models.UUIDField()),
                ('value', models.FloatField()),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_kpi_snapshots',
                'indexes': [models.Index(fields=['kpi_name', 'snapshot_date'], name='analytics_k_kpi_nam_095527_idx')],
            },
        ),
    ]
