# Generated by Django 6.0.6 on 2026-06-10 19:56

import saas_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=saas_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(unique=True)),
                ('tier', models.CharField(max_length=50)),
                ('billing_status', models.CharField(max_length=50)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saas_tenant_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='WhiteLabelConfig',
            fields=[
                ('id', models.UUIDField(default=saas_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('language_pack', models.CharField(default='en', max_length=10)),
            ],
            options={
                'db_table': 'saas_whitelabel_configs',
            },
        ),
    ]
