# Generated by Django 6.0.6 on 2026-06-10 19:56

import care_management_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareCase',
            fields=[
                ('id', models.UUIDField(default=care_management_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('case_manager_id', models.UUIDField()),
                ('primary_diagnosis', models.CharField(max_length=200)),
                ('risk_level', models.CharField(max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'care_cases',
            },
        ),
        migrations.CreateModel(
            name='DischargePlan',
            fields=[
                ('id', models.UUIDField(default=care_management_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('target_discharge_date', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('readmission_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(default='PLANNING', max_length=50)),
            ],
            options={
                'db_table': 'care_discharge_plans',
            },
        ),
    ]
