# Generated by Django 6.0.6 on 2026-06-10 19:56

import nursing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=nursing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('created_by', models.UUIDField()),
                ('goals', models.TextField()),
                ('interventions', models.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nursing_care_plans',
            },
        ),
        migrations.CreateModel(
            name='FluidBalance',
            fields=[
                ('id', models.UUIDField(default=nursing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('recorded_by', models.UUIDField()),
                ('fluid_type', models.CharField(max_length=50)),
                ('fluid_name', models.CharField(max_length=100)),
                ('volume_ml', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nursing_fluid_balances',
            },
        ),
        migrations.CreateModel(
            name='NursingAssessment',
            fields=[
                ('id', models.UUIDField(default=nursing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('nurse_id', models.UUIDField()),
                ('assessment_type', models.CharField(max_length=100)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField()),
                ('conducted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nursing_assessments',
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=nursing_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField(help_text='Reference to patient_app.Encounter')),
                ('patient_id', models.UUIDField()),
                ('recorded_by', models.UUIDField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('pain_score', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nursing_vital_signs',
                'indexes': [models.Index(fields=['encounter_id', '-recorded_at'], name='nursing_vit_encount_fdb776_idx')],
            },
        ),
    ]
