# Generated by Django 6.0.6 on 2026-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbag',
            name='blood_group',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='crossmatched_patient_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='donor_id',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='rh_factor',
            field=models.CharField(default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='volume_ml',
            field=models.IntegerField(default=450),
        ),
        migrations.AlterField(
            model_name='bloodbag',
            name='patient_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbag',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=50),
        ),
    ]
