# Generated by Django 6.0.6 on 2026-06-15 12:23

import django.db.models.deletion
import hr_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, help_text='Generic reference to auth_app.Facility', null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_departments',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('annual_days', models.IntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_doc', models.BooleanField(default=False, help_text='Medical certificate required')),
                ('carry_forward', models.BooleanField(default=False)),
                ('max_carry_days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'hr_leave_types',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hr_shifts',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.department')),
            ],
            options={
                'db_table': 'hr_designations',
            },
        ),
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_app.designation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_healthcare_professionals',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Present', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.healthcareprofessional')),
            ],
            options={
                'db_table': 'hr_attendances',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('document', models.CharField(blank=True, help_text='File path to supporting document', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr_app.healthcareprofessional')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr_app.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_requests',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('kpi_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('goals_next', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hr_app.healthcareprofessional')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_performance_reviews',
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('roster_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.healthcareprofessional')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.shift')),
            ],
            options={
                'db_table': 'hr_duty_rosters',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=hr_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='BLS|ACLS|Infection Control|Fire Safety|Other', max_length=100)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('completed_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_ref', models.CharField(blank=True, max_length=255)),
                ('cpd_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hr_app.healthcareprofessional')),
            ],
            options={
                'db_table': 'hr_training_records',
            },
        ),
    ]
