# Generated by Django 6.0.6 on 2026-06-10 19:56

import ai_platform.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiCache',
            fields=[
                ('id', models.UUIDField(default=ai_platform.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('query_hash', models.CharField(max_length=255, unique=True)),
                ('response_payload', models.JSONField()),
                ('intent', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_cache',
            },
        ),
        migrations.CreateModel(
            name='AiIntent',
            fields=[
                ('id', models.UUIDField(default=ai_platform.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ai_intents',
            },
        ),
        migrations.CreateModel(
            name='AiProvider',
            fields=[
                ('id', models.UUIDField(default=ai_platform.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(max_length=50)),
                ('base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key_secret_name', models.CharField(help_text='Reference to secrets manager', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ai_providers',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='AiTemplate',
            fields=[
                ('id', models.UUIDField(default=ai_platform.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prompt_template', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_platform.aiintent')),
            ],
            options={
                'db_table': 'ai_templates',
            },
        ),
        migrations.CreateModel(
            name='AiTokenUsage',
            fields=[
                ('id', models.UUIDField(default=ai_platform.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('task_intent', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_platform.aiprovider')),
            ],
            options={
                'db_table': 'ai_token_usage',
            },
        ),
    ]
