# Generated by Django 6.0.6 on 2026-06-10 19:56

import governance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityReview',
            fields=[
                ('id', models.UUIDField(default=governance_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('date_of_death', models.DateTimeField()),
                ('reviewer_id', models.UUIDField()),
                ('findings', models.TextField()),
                ('is_preventable', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
            options={
                'db_table': 'gov_mortality_reviews',
            },
        ),
        migrations.CreateModel(
            name='QualityIndicator',
            fields=[
                ('id', models.UUIDField(default=governance_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gov_quality_indicators',
            },
        ),
        migrations.CreateModel(
            name='SentinelEvent',
            fields=[
                ('id', models.UUIDField(default=governance_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField(blank=True, null=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reported_by', models.UUIDField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='UNDER_INVESTIGATION', max_length=50)),
                ('root_cause_analysis', models.TextField(blank=True, null=True)),
                ('action_plan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gov_sentinel_events',
            },
        ),
    ]
