# Generated by Django 6.0.6 on 2026-06-10 19:56

import customer_success_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHealthScore',
            fields=[
                ('id', models.UUIDField(default=customer_success_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(unique=True)),
                ('adoption_metric', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('training_completion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('health_status', models.CharField(default='AT_RISK', max_length=50)),
            ],
            options={
                'db_table': 'cs_health_scores',
            },
        ),
    ]
