# Generated by Django 6.0.6 on 2026-06-10 19:56

import research_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCohort',
            fields=[
                ('id', models.UUIDField(default=research_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('criteria', models.JSONField()),
                ('patient_count', models.IntegerField(default=0)),
                ('principal_investigator', models.UUIDField()),
            ],
            options={
                'db_table': 'research_cohorts',
            },
        ),
    ]
