# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import lab_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=lab_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('encounter_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('ordering_physician_id', models.UUIDField()),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lab_orders',
            },
        ),
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('id', models.UUIDField(default=lab_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('terminology_concept_id', models.UUIDField(help_text='LOINC Code')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lab_panels',
            },
        ),
        migrations.CreateModel(
            name='LabSpecimen',
            fields=[
                ('id', models.UUIDField(default=lab_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('specimen_type', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('collected_by', models.UUIDField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('received_in_lab_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='lab_app.laborder')),
            ],
            options={
                'db_table': 'lab_specimens',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=lab_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('terminology_concept_id', models.UUIDField(blank=True, help_text='LOINC code for specific test', null=True)),
                ('test_name', models.CharField(max_length=255)),
                ('result_value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDING_VALIDATION', max_length=50)),
                ('finalized_by', models.UUIDField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab_app.laborder')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_app.labpanel')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_app.labspecimen')),
            ],
            options={
                'db_table': 'lab_results',
            },
        ),
    ]
