# Generated by Django 6.0.6 on 2026-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('appointment_id', models.IntegerField(blank=True, null=True)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('encounter_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_clinical_encounters',
            },
        ),
        migrations.CreateModel(
            name='MedicationSafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('prescription_id', models.IntegerField(blank=True, null=True)),
                ('allergy_checked', models.BooleanField(default=False)),
                ('dose_checked', models.BooleanField(default=False)),
                ('interaction_checked', models.BooleanField(default=False)),
                ('pregnancy_checked', models.BooleanField(default=False)),
                ('renal_adjustment_checked', models.BooleanField(default=False)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('checked_by', models.IntegerField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_medication_safety_checks',
            },
        ),
        migrations.CreateModel(
            name='SurgicalSafetyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('surgery_id', models.IntegerField(blank=True, null=True)),
                ('sign_in_identity_confirmed', models.BooleanField(default=False)),
                ('sign_in_site_marked', models.BooleanField(default=False)),
                ('sign_in_anaesthesia_safety_check', models.BooleanField(default=False)),
                ('sign_in_pulse_oximeter_working', models.BooleanField(default=False)),
                ('time_out_team_introduced', models.BooleanField(default=False)),
                ('time_out_patient_procedure_site_confirmed', models.BooleanField(default=False)),
                ('time_out_antibiotic_prophylaxis_confirmed', models.BooleanField(default=False)),
                ('time_out_critical_events_reviewed', models.BooleanField(default=False)),
                ('sign_out_procedure_recorded', models.BooleanField(default=False)),
                ('sign_out_instrument_counts_confirmed', models.BooleanField(default=False)),
                ('sign_out_specimen_labelled', models.BooleanField(default=False)),
                ('sign_out_recovery_concerns_reviewed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hospital_surgical_safety_checklists',
            },
        ),
    ]
