# Generated by Django 6.0.6 on 2026-06-15 12:23

import asset_management_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=asset_management_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('depreciation_method', models.CharField(default='straight_line', help_text='straight_line|declining_balance', max_length=20)),
                ('salvage_pct', models.DecimalField(decimal_places=2, default=0, help_text='Residual value as % of cost', max_digits=5)),
            ],
            options={
                'db_table': 'asset_categories',
            },
        ),
        migrations.CreateModel(
            name='BiomedicalAsset',
            fields=[
                ('id', models.UUIDField(default=asset_management_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('department_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Operational', max_length=50)),
                ('next_calibration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_biomedical_assets',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=asset_management_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('facility_id', models.UUIDField(blank=True, null=True)),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('in_service', 'In Service'), ('maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned'), ('disposed', 'Disposed')], default='in_service', max_length=20)),
                ('insurance_policy', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('next_calibration', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset_management_app.assetcategory')),
            ],
            options={
                'db_table': 'asset_register',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=asset_management_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('performed_by', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_management_app.biomedicalasset')),
            ],
            options={
                'db_table': 'asset_maintenance_logs',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.UUIDField(default=asset_management_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('calibration', 'Calibration')], max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=15)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('vendor_id', models.UUIDField(blank=True, help_text='AMC vendor', null=True)),
                ('description', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('downtime_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_orders', to='asset_management_app.asset')),
            ],
            options={
                'db_table': 'asset_maintenance_orders',
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.UUIDField(default=asset_management_app.models._uuid7, editable=False, primary_key=True, serialize=False)),
                ('period_date', models.DateField(help_text='First day of the month')),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_dep', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('posted', models.BooleanField(default=False)),
                ('journal_entry_id', models.UUIDField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_schedule', to='asset_management_app.asset')),
            ],
            options={
                'db_table': 'asset_depreciation_schedule',
                'ordering': ['period_date'],
                'unique_together': {('asset', 'period_date')},
            },
        ),
    ]
