# Generated by Django 6.0.6 on 2026-06-10 19:56

import admission_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bed_app', '0001_initial'),
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=admission_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='scheduled', max_length=50)),
                ('admission_time', models.DateTimeField(blank=True, null=True)),
                ('discharge_time', models.DateTimeField(blank=True, null=True)),
                ('admitting_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_handled', to='hr_app.healthcareprofessional')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_admissions', to='bed_app.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patient_app.patient')),
            ],
            options={
                'db_table': 'clinical_admission',
            },
        ),
    ]
