# Generated by Django 6.0.6 on 2026-06-10 19:56

import support_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=support_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('reporter_id', models.UUIDField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='OPEN', max_length=50)),
                ('priority', models.CharField(default='NORMAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
    ]
