# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import insurance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=insurance_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('insurance_provider_id', models.UUIDField(help_text='Reference to External Organization')),
                ('policy_number', models.CharField(max_length=100)),
                ('group_number', models.CharField(blank=True, max_length=100, null=True)),
                ('subscriber_name', models.CharField(max_length=255)),
                ('relationship_to_subscriber', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'insurance_policies',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=insurance_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('invoice_id', models.UUIDField(help_text='Reference to Invoice')),
                ('claim_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('total_claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('adjudicated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurancepolicy')),
            ],
            options={
                'db_table': 'insurance_claims',
            },
        ),
    ]
