# Generated by Django 6.0.6 on 2026-06-10 19:56

import django.db.models.deletion
import event_catalog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseEvent',
            fields=[
                ('id', models.UUIDField(default=event_catalog_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(help_text='e.g., PatientRegistered, EncounterOpened', max_length=150, unique=True)),
                ('domain_owner', models.CharField(max_length=100)),
                ('payload_schema', models.JSONField(help_text='JSON schema definition for the event payload')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'enterprise_events',
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.UUIDField(default=event_catalog_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('subscriber_domain', models.CharField(max_length=100)),
                ('handler_endpoint', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='event_catalog_app.enterpriseevent')),
            ],
            options={
                'db_table': 'event_subscriptions',
            },
        ),
    ]
