# Generated by Django 6.0.6 on 2026-06-10 19:56

import knowledge_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalGuideline',
            fields=[
                ('id', models.UUIDField(default=knowledge_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('source_organization', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'know_clinical_guidelines',
            },
        ),
        migrations.CreateModel(
            name='StandardOperatingProcedure',
            fields=[
                ('id', models.UUIDField(default=knowledge_app.models.generate_uuidv7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'know_sops',
            },
        ),
    ]
